"""
Figure 7c — Gene expression heatmap, cardio development
Standalone reproduction of Figure7/plot_significant_heatmap.ipynb

Input: Figure7/cardio_deseq2_cubicsplines_output/fitted_trajectories_all_genes.csv
       (DESeq2 cubic spline fitted/observed trajectories — generated by the R analysis)

Outputs to: refactoring_roadmap/fig7c_plots/
  fig7c_heatmap_all_significant.{svg,png}  — all 146 significant genes (padj < 0.05)

Notebook helper outputs remain available in code, but are disabled by default:
  fig7c_heatmap_top50.{svg,png}
  fig7c_heatmap_mesoderm_markers.{svg,png}
  fig7c_heatmap_cardiac_markers.{svg,png}
"""

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from ntvetools import load_gtf_df

def find_root() -> Path:
    here = Path(__file__).resolve()
    for candidate in (here.parent, here.parent.parent):
        if (candidate / "resources").exists():
            return candidate
    return here.parent.parent

ROOT = find_root()
OUT_DIR = Path(__file__).parent / "fig7c_plots"
OUT_DIR.mkdir(exist_ok=True)

GTF_PATH = ROOT / "resources" / "merged_gtf_homosapiens_v108_musmusculus_v109.csv.gz"
TRAJECTORIES_CSV = ROOT / "Figure7" / "cardio_deseq2_cubicsplines_output" / "fitted_trajectories_all_genes.csv"

plt.rcParams["svg.fonttype"] = "none"
plt.rcParams["font.size"] = 8

PSEUDOCOUNT = 0.1
PADJ_THRESHOLD = 0.05
MESODERM_MARKERS = ["MIXL1", "PDGFRA"]
CARDIAC_MARKERS = ["ACTN2", "TNNT2", "MYL7"]


# --- Load reference data ---
print("Loading GTF data...")
gtf_data = load_gtf_df(str(GTF_PATH))
gene_id_to_name = gtf_data["gene_id_to_name"]
gene_name_to_id = {v: k for k, v in gene_id_to_name.items()}

# --- Load and transform trajectories ---
print("Loading trajectories...")
if not TRAJECTORIES_CSV.exists():
    raise FileNotFoundError(
        "Missing fitted cardio trajectories. Run `fig7c_pipeline.py` first to generate "
        f"{ROOT / 'Figure7' / 'cardio_deseq2_cubicsplines_output' / 'fitted_trajectories_all_genes.csv'}."
    )
trajectories = pd.read_csv(TRAJECTORIES_CSV)
print(f"  {trajectories['Gene'].nunique()} genes, "
      f"timepoints: {sorted(trajectories['Time'].unique())}")

# Pivot observed values to gene × timepoint matrix
obs = trajectories.pivot(index="Gene", columns="Time", values="Observed")

# Log2 transform + mean-centre per gene (across timepoints)
obs_log = np.log2(obs + PSEUDOCOUNT)
obs_log_centred = obs_log.sub(obs_log.mean(axis=1), axis=0)

# padj is constant per gene across timepoints — take first occurrence
gene_padj = trajectories.groupby("Gene")["padj"].first()
sig_genes = gene_padj[gene_padj < PADJ_THRESHOLD].index
filtered = obs_log_centred.loc[obs_log_centred.index.isin(sig_genes)]
print(f"Significant genes (padj < {PADJ_THRESHOLD}): {len(filtered)}")

# Sort by timepoint of peak expression
filtered_sorted = filtered.loc[filtered.idxmax(axis=1).sort_values().index]


# --- Plotting helpers ---

def make_heatmap(
    data: pd.DataFrame,
    y_labels: list[str] | None,
    title: str,
    figsize: tuple[float, float],
) -> plt.Figure:
    fig, ax = plt.subplots(figsize=figsize)
    vmin = np.percentile(data.values, 2)
    vmax = np.percentile(data.values, 98)
    im = ax.imshow(
        data.values, cmap="RdBu_r", aspect="auto",
        vmin=vmin, vmax=vmax, interpolation="nearest",
    )
    ax.set_xlabel("Timepoint (days)", fontsize=8, fontweight="bold")
    ax.set_xticks(range(len(data.columns)))
    ax.set_xticklabels(data.columns.astype(int), rotation=0, fontsize=8)
    if y_labels is not None:
        ax.set_yticks(range(len(data)))
        ax.set_yticklabels(y_labels, fontsize=max(4, 60 / len(data)))
        ax.set_ylabel("Gene", fontsize=8, fontweight="bold")
    else:
        ax.set_yticks([])
        ax.set_ylabel(f"Genes (n={len(data)})", fontsize=8, fontweight="bold")
    ax.set_title(title, fontsize=8, fontweight="bold", pad=10)
    cbar = plt.colorbar(im, ax=ax, shrink=0.8)
    cbar.ax.tick_params(labelsize=8)
    cbar.set_label("log₂(Expression) − Mean", fontsize=8)
    fig.tight_layout()
    return fig


def save_plot(fig: plt.Figure, stem: str) -> None:
    for ext in ("svg", "png"):
        out = OUT_DIR / f"{stem}.{ext}"
        fig.savefig(out, format=ext, bbox_inches="tight", dpi=150)
        print(f"Saved: {out}")


# --- Plot 1: All significant genes ---
y_labels_all = [gene_id_to_name.get(g, g) for g in filtered_sorted.index]
fig = make_heatmap(
    filtered_sorted,
    y_labels_all,
    f"Gene Expression — Cardio Development\n"
    f"({len(filtered_sorted)} genes, padj < {PADJ_THRESHOLD}, log₂-centred)",
    figsize=(7, 20),
)
save_plot(fig, "fig7c_heatmap_all_significant")
plt.close(fig)

# Notebook helper outputs intentionally disabled by default:
#
# top50_ids = gene_padj.dropna().sort_values().head(50).index
# top50 = filtered.loc[top50_ids]
# top50_sorted = top50.loc[top50.idxmax(axis=1).sort_values().index]
# fig = make_heatmap(
#     top50_sorted,
#     [gene_id_to_name.get(g, g) for g in top50_sorted.index],
#     "Top 50 Most Significant Genes — Cardio Development\n(log₂-centred)",
#     figsize=(8, 6),
# )
# save_plot(fig, "fig7c_heatmap_top50")
# plt.close(fig)
#
# for markers, stem, title in [
#     (
#         MESODERM_MARKERS,
#         "fig7c_heatmap_mesoderm_markers",
#         "Mesoderm Markers — Cardio Development\n(log₂-centred)",
#     ),
#     (
#         CARDIAC_MARKERS,
#         "fig7c_heatmap_cardiac_markers",
#         "Cardiac Markers — Cardio Development\n(log₂-centred)",
#     ),
# ]:
#     ids = [gene_name_to_id[m] for m in markers if m in gene_name_to_id]
#     data = obs_log_centred.loc[obs_log_centred.index.isin(ids)]
#     data = data.loc[data.idxmax(axis=1).sort_values().index]
#     fig = make_heatmap(
#         data,
#         [gene_id_to_name.get(g, g) for g in data.index],
#         title,
#         figsize=(4, 1.5),
#     )
#     save_plot(fig, stem)
#     plt.close(fig)

print("Done.")
